// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcMFlCuo7yrokV0bPX7ZfDUqCQrDpDGHo',
    appId: '1:418416658942:web:fe1349dd2c119c2eff98af',
    messagingSenderId: '418416658942',
    projectId: 'carconnect-bbb35',
    authDomain: 'carconnect-bbb35.firebaseapp.com',
    storageBucket: 'carconnect-bbb35.firebasestorage.app',
    measurementId: 'G-8HTE3PGK4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVkuM-C5ftvFa0Neu897G52I5MxBCejUY',
    appId: '1:418416658942:android:39159049c7bbc721ff98af',
    messagingSenderId: '418416658942',
    projectId: 'carconnect-bbb35',
    storageBucket: 'carconnect-bbb35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNHWbolhLZm4jDHLQ5jKTk5SLAtQezgIU',
    appId: '1:418416658942:ios:4531586c8a88e9b5ff98af',
    messagingSenderId: '418416658942',
    projectId: 'carconnect-bbb35',
    storageBucket: 'carconnect-bbb35.firebasestorage.app',
    iosClientId: '418416658942-o2q1mki4lqiuhgncl7314h0rh92liev8.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNHWbolhLZm4jDHLQ5jKTk5SLAtQezgIU',
    appId: '1:418416658942:ios:4531586c8a88e9b5ff98af',
    messagingSenderId: '418416658942',
    projectId: 'carconnect-bbb35',
    storageBucket: 'carconnect-bbb35.firebasestorage.app',
    iosClientId: '418416658942-o2q1mki4lqiuhgncl7314h0rh92liev8.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcMFlCuo7yrokV0bPX7ZfDUqCQrDpDGHo',
    appId: '1:418416658942:web:1ef563d932d5b8e4ff98af',
    messagingSenderId: '418416658942',
    projectId: 'carconnect-bbb35',
    authDomain: 'carconnect-bbb35.firebaseapp.com',
    storageBucket: 'carconnect-bbb35.firebasestorage.app',
    measurementId: 'G-DXR884VQD1',
  );
}
